pep_version: 2.1.0
sample_table: synthetic_list.csv
sample_modifiers:
  append:
    chrom_sizes: ${CHROMSIZESPATH} #"/home/drc/GITHUB/gtars/gtars/tests/hg38.chrom.sizes"
    gtars_path : ${GTARSPATH} #"/home/drc/GITHUB/gtars/gtars/target/release/gtars"